#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Heidenhain (海德汉) G代码生成器
实现海德汉控制器特定的程序生成
"""

import os
import time
from base_gcode_generator import BaseGcodeGenerator

class HeidenhainGcodeGenerator(BaseGcodeGenerator):
    """Heidenhain CNC控制器程序生成器"""
    
    def __init__(self, feed_rate=500, safety_height=10, cut_depth=0.5, tool_number=1, spindle_speed=1000):
        """
        初始化Heidenhain程序生成器
        
        参数:
        feed_rate (float): 进给速度 (mm/min)
        safety_height (float): 安全高度 (mm)
        cut_depth (float): 切削深度 (mm)
        tool_number (int): 刀具号
        spindle_speed (int): 主轴转速 (RPM)
        """
        super().__init__(feed_rate, safety_height, cut_depth)
        self.tool_number = int(tool_number)
        self.spindle_speed = int(spindle_speed)
    
    def generate_header(self):
        """生成Heidenhain程序头"""
        header = []
        header.append("BEGIN PGM STP_CONVERSION MM")
        header.append("; GENERATED BY STP-TO-GCODE CONVERTER")
        header.append(f"; DATE: {time.strftime('%Y-%m-%d %H:%M:%S')}")
        header.append(f"TOOL CALL {self.tool_number} Z S{self.spindle_speed}")  # 刀具调用
        header.append("L Z+{} R0 F MAX".format(self.format_coordinate(self.safety_height)))
        header.append("L X+0 Y+0 R0 F MAX")  # 快速移动到原点
        return header
    
    def generate_footer(self):
        """生成Heidenhain程序尾"""
        footer = []
        footer.append("L Z+{} R0 F MAX".format(self.format_coordinate(self.safety_height)))
        footer.append("L X+0 Y+0 R0 F MAX")
        footer.append("M30")  # 程序结束
        footer.append("END PGM STP_CONVERSION MM")
        return footer
    
    def generate_linear_move(self, x, y, z, feed=None):
        """生成Heidenhain直线移动指令(L)"""
        if feed is None:
            feed = self.feed_rate
            
        cmd = "L"
        
        if x is not None:
            cmd += " X+{}".format(self.format_coordinate(x))
            self.current_position["x"] = x
            
        if y is not None:
            cmd += " Y+{}".format(self.format_coordinate(y))
            self.current_position["y"] = y
            
        if z is not None:
            cmd += " Z+{}".format(self.format_coordinate(z))
            self.current_position["z"] = z
            
        cmd += " R0 F{}".format(feed)
        
        return cmd
    
    def generate_rapid_move(self, x=None, y=None, z=None):
        """生成Heidenhain快速移动指令(L...F MAX)"""
        cmd = "L"
        
        if x is not None:
            cmd += " X+{}".format(self.format_coordinate(x))
            self.current_position["x"] = x
            
        if y is not None:
            cmd += " Y+{}".format(self.format_coordinate(y))
            self.current_position["y"] = y
            
        if z is not None:
            cmd += " Z+{}".format(self.format_coordinate(z))
            self.current_position["z"] = z
            
        cmd += " R0 F MAX"
        
        return cmd
    
    def set_working_plane(self, plane="xy"):
        """设置Heidenhain工作平面"""
        if plane == "xy":
            return "TOOL AXIS Z"  # 海德汉通过刀具轴定义平面
        elif plane == "xz":
            return "TOOL AXIS Y"
        elif plane == "yz":
            return "TOOL AXIS X"
        else:
            raise ValueError(f"不支持的平面: {plane}")
    
    def set_units(self, units="mm"):
        """设置Heidenhain单位"""
        # 海德汉在程序开始定义单位，此处无操作
        return ""
    
    def set_coordinate_system(self, system=1):
        """设置Heidenhain坐标系"""
        if 1 <= system <= 9:
            return f"CYCL DEF 7.0 DATUM SHIFT\nCYCL DEF 7.1 #{system}"
        else:
            raise ValueError(f"坐标系编号必须在1-9范围内，当前值: {system}")
    
    def set_tool(self, tool_number, spindle_speed=None):
        """设置刀具"""
        self.tool_number = tool_number
        if spindle_speed is None:
            spindle_speed = self.spindle_speed
        else:
            self.spindle_speed = spindle_speed
        return f"TOOL CALL {tool_number} Z S{spindle_speed}"
    
    def coolant_on(self):
        """冷却液开启"""
        return "M8"
    
    def coolant_off(self):
        """冷却液关闭"""
        return "M9"
    
    def circular_move(self, x, y, z, i, j, k, direction="cw", feed=None):
        """生成圆弧移动指令"""
        if feed is None:
            feed = self.feed_rate
            
        cmd = "CC"
        
        # 海德汉用CC命令设置圆心
        if i is not None and j is not None:
            cmd_cc = f"CC X+{self.format_coordinate(i)} Y+{self.format_coordinate(j)}"
        else:
            raise ValueError("圆弧移动需要指定圆心坐标")
        
        # 圆弧移动命令
        if direction == "cw":
            cmd_arc = "C"  # 顺时针
        else:
            cmd_arc = "CP"  # 逆时针
            
        cmd_arc += f" X+{self.format_coordinate(x)} Y+{self.format_coordinate(y)}"
        
        if z is not None:
            cmd_arc += f" Z+{self.format_coordinate(z)}"
            
        cmd_arc += f" R0 F{feed}"
        
        self.current_position.update({"x": x, "y": y})
        if z is not None:
            self.current_position["z"] = z
            
        return [cmd_cc, cmd_arc]  # 返回两行命令 