#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Siemens (西门子) SINUMERIK G代码生成器
实现西门子控制器特定的G代码生成
"""

import os
import time
from base_gcode_generator import BaseGcodeGenerator

class SiemensGcodeGenerator(BaseGcodeGenerator):
    """Siemens SINUMERIK CNC控制器G代码生成器"""
    
    def __init__(self, feed_rate=500, safety_height=10, cut_depth=0.5, tool_number=1, spindle_speed=1000):
        """
        初始化Siemens G代码生成器
        
        参数:
        feed_rate (float): 进给速度 (mm/min)
        safety_height (float): 安全高度 (mm)
        cut_depth (float): 切削深度 (mm)
        tool_number (int): 刀具号
        spindle_speed (int): 主轴转速 (RPM)
        """
        super().__init__(feed_rate, safety_height, cut_depth)
        self.tool_number = int(tool_number)
        self.spindle_speed = int(spindle_speed)
    
    def generate_header(self):
        """生成Siemens程序头"""
        header = []
        header.append("; SIEMENS SINUMERIK PROGRAM")
        header.append("; GENERATED BY STP-TO-GCODE CONVERTER")
        header.append(f"; DATE: {time.strftime('%Y-%m-%d %H:%M:%S')}")
        header.append("PROG_NAME")
        header.append("MSG(\"STP TO GCODE CONVERSION\")")
        header.append("G90 G17 G71")  # 绝对坐标、XY平面、公制
        header.append("WORKPIECE(,,,\"CYLINDER\",,,\"ZA\",200,150)")  # 工件定义示例
        header.append(f"T=\"T{self.tool_number}\"")  # 选择刀具
        header.append(f"M6")  # 换刀
        header.append(f"S{self.spindle_speed} M3")  # 主轴速度和方向
        header.append(f"G0 X0 Y0 Z{self.format_coordinate(self.safety_height)}")
        return header
    
    def generate_footer(self):
        """生成Siemens程序尾"""
        footer = []
        footer.append(f"G0 Z{self.format_coordinate(self.safety_height)}")
        footer.append("G0 X0 Y0")
        footer.append("M5")  # 主轴停止
        footer.append("M30")  # 程序结束
        return footer
    
    def generate_linear_move(self, x, y, z, feed=None):
        """生成Siemens直线移动指令(G1)"""
        if feed is None:
            feed = self.feed_rate
            
        cmd = "G1"
        
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}"
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}"
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}"
            self.current_position["z"] = z
            
        cmd += f" F={feed}"
        
        return cmd
    
    def generate_rapid_move(self, x=None, y=None, z=None):
        """生成Siemens快速移动指令(G0)"""
        cmd = "G0"
        
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}"
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}"
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}"
            self.current_position["z"] = z
            
        return cmd
    
    def set_working_plane(self, plane="xy"):
        """设置Siemens工作平面"""
        if plane == "xy":
            return "G17"  # XY平面
        elif plane == "xz":
            return "G18"  # XZ平面
        elif plane == "yz":
            return "G19"  # YZ平面
        else:
            raise ValueError(f"不支持的平面: {plane}")
    
    def set_units(self, units="mm"):
        """设置Siemens单位"""
        if units == "mm":
            return "G71"  # 公制
        elif units == "inch":
            return "G70"  # 英制
        else:
            raise ValueError(f"不支持的单位: {units}")
    
    def set_coordinate_system(self, system=1):
        """设置Siemens坐标系"""
        if 1 <= system <= 6:
            if system == 1:
                return "G54"
            elif system == 2:
                return "G55"
            elif system == 3:
                return "G56"
            elif system == 4:
                return "G57"
            elif system == 5:
                return "G505"
            elif system == 6:
                return "G506"
        else:
            raise ValueError(f"坐标系编号必须在1-6范围内，当前值: {system}")
    
    def tool_radius_comp_on(self, direction="left"):
        """刀具半径补偿开启"""
        if direction == "left":
            return "G41"
        elif direction == "right":
            return "G42"
        else:
            raise ValueError(f"不支持的补偿方向: {direction}")
    
    def tool_radius_comp_off(self):
        """刀具半径补偿关闭"""
        return "G40"
    
    def coolant_on(self):
        """冷却液开启"""
        return "M8"
    
    def coolant_off(self):
        """冷却液关闭"""
        return "M9" 