#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
FANUC G代码生成器
实现FANUC控制器特定的G代码生成
"""

import os
import time
from base_gcode_generator import BaseGcodeGenerator

class FanucGcodeGenerator(BaseGcodeGenerator):
    """FANUC CNC控制器G代码生成器"""
    
    def __init__(self, feed_rate=500, safety_height=10, cut_depth=0.5, tool_number=1, spindle_speed=1000):
        """
        初始化FANUC G代码生成器
        
        参数:
        feed_rate (float): 进给速度 (mm/min)
        safety_height (float): 安全高度 (mm)
        cut_depth (float): 切削深度 (mm)
        tool_number (int): 刀具号
        spindle_speed (int): 主轴转速 (RPM)
        """
        super().__init__(feed_rate, safety_height, cut_depth)
        self.tool_number = int(tool_number)
        self.spindle_speed = int(spindle_speed)
        self.line_number = 10
        self.line_increment = 10
    
    def _get_line_number(self):
        """获取并递增行号"""
        current = self.line_number
        self.line_number += self.line_increment
        return current
    
    def generate_header(self):
        """生成FANUC程序头"""
        header = []
        header.append("%")
        header.append("O1000")
        header.append(f"(PROGRAM GENERATED BY STP-TO-GCODE CONVERTER)")
        header.append(f"(DATE: {time.strftime('%Y-%m-%d %H:%M:%S')})")
        header.append(f"N{self._get_line_number()} G90 G17 G21")  # 绝对坐标、XY平面、毫米
        header.append(f"N{self._get_line_number()} G54")  # 工件坐标系
        header.append(f"N{self._get_line_number()} G00 X0 Y0 Z{self.format_coordinate(self.safety_height)}")
        header.append(f"N{self._get_line_number()} M06 T{self.tool_number}")  # 刀具选择
        header.append(f"N{self._get_line_number()} M03 S{self.spindle_speed}")  # 主轴启动，设置转速
        header.append(f"N{self._get_line_number()} G43 H{self.tool_number}")  # 刀具长度补偿
        return header
    
    def generate_footer(self):
        """生成FANUC程序尾"""
        footer = []
        footer.append(f"N{self._get_line_number()} G00 Z{self.format_coordinate(self.safety_height)}")
        footer.append(f"N{self._get_line_number()} G00 X0 Y0")
        footer.append(f"N{self._get_line_number()} M05")  # 主轴停止
        footer.append(f"N{self._get_line_number()} M30")  # 程序结束
        footer.append("%")
        return footer
    
    def generate_linear_move(self, x, y, z, feed=None):
        """生成FANUC直线移动指令(G01)"""
        if feed is None:
            feed = self.feed_rate
            
        cmd = f"N{self._get_line_number()} G01"
        
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}"
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}"
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}"
            self.current_position["z"] = z
            
        cmd += f" F{feed}"
        
        return cmd
    
    def generate_rapid_move(self, x=None, y=None, z=None):
        """生成FANUC快速移动指令(G00)"""
        cmd = f"N{self._get_line_number()} G00"
        
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}"
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}"
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}"
            self.current_position["z"] = z
            
        return cmd
    
    def set_working_plane(self, plane="xy"):
        """设置FANUC工作平面"""
        if plane == "xy":
            return f"N{self._get_line_number()} G17"
        elif plane == "xz":
            return f"N{self._get_line_number()} G18"
        elif plane == "yz":
            return f"N{self._get_line_number()} G19"
        else:
            raise ValueError(f"不支持的平面: {plane}")
    
    def set_units(self, units="mm"):
        """设置FANUC单位"""
        if units == "mm":
            return f"N{self._get_line_number()} G21"
        elif units == "inch":
            return f"N{self._get_line_number()} G20"
        else:
            raise ValueError(f"不支持的单位: {units}")
    
    def set_coordinate_system(self, system=1):
        """设置FANUC坐标系"""
        if 1 <= system <= 6:
            g_code = 53 + system  # G54-G59
            return f"N{self._get_line_number()} G{g_code}"
        else:
            raise ValueError(f"坐标系编号必须在1-6范围内，当前值: {system}")
    
    def set_tool(self, tool_number):
        """设置刀具"""
        self.tool_number = tool_number
        return f"N{self._get_line_number()} M06 T{tool_number}"
    
    def set_spindle_speed(self, speed, direction="cw"):
        """设置主轴转速"""
        self.spindle_speed = speed
        if direction == "cw":
            return f"N{self._get_line_number()} M03 S{speed}"
        else:
            return f"N{self._get_line_number()} M04 S{speed}"
    
    def coolant_on(self, type="flood"):
        """冷却液开启"""
        if type == "flood":
            return f"N{self._get_line_number()} M08"
        elif type == "mist":
            return f"N{self._get_line_number()} M07"
        else:
            raise ValueError(f"不支持的冷却类型: {type}")
    
    def coolant_off(self):
        """冷却液关闭"""
        return f"N{self._get_line_number()} M09" 