#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Haas (哈斯) G代码生成器
实现哈斯控制器特定的G代码生成
"""

import os
import time
from base_gcode_generator import BaseGcodeGenerator

class HaasGcodeGenerator(BaseGcodeGenerator):
    """Haas CNC控制器G代码生成器"""
    
    def __init__(self, feed_rate=500, safety_height=10, cut_depth=0.5, tool_number=1, spindle_speed=1000):
        """
        初始化Haas G代码生成器
        
        参数:
        feed_rate (float): 进给速度 (mm/min)
        safety_height (float): 安全高度 (mm)
        cut_depth (float): 切削深度 (mm)
        tool_number (int): 刀具号
        spindle_speed (int): 主轴转速 (RPM)
        """
        super().__init__(feed_rate, safety_height, cut_depth)
        self.tool_number = int(tool_number)
        self.spindle_speed = int(spindle_speed)
        self.program_number = 1000
        self.line_number = 10
        self.line_increment = 5
    
    def _get_line_number(self):
        """获取并递增行号"""
        current = self.line_number
        self.line_number += self.line_increment
        return current
    
    def generate_header(self):
        """生成Haas程序头"""
        header = []
        header.append(f"O{self.program_number}")
        header.append(f"(PROGRAM GENERATED BY STP-TO-GCODE CONVERTER)")
        header.append(f"(DATE: {time.strftime('%Y-%m-%d %H:%M:%S')})")
        header.append(f"N{self._get_line_number()} G40 G49 G50 G80")  # 取消所有补偿
        header.append(f"N{self._get_line_number()} G90 G20 G17")  # 绝对坐标、英寸、XY平面
        # 如果使用公制单位，需要切换
        header.append(f"N{self._get_line_number()} G21")  # 切换到毫米
        header.append(f"N{self._get_line_number()} G54")  # 工件坐标系
        header.append(f"N{self._get_line_number()} G00 X0. Y0. Z{self.format_coordinate(self.safety_height)}")
        header.append(f"N{self._get_line_number()} T{self.tool_number} M06")  # 选择并更换刀具
        header.append(f"N{self._get_line_number()} S{self.spindle_speed} M03")  # 设置转速并启动主轴
        header.append(f"N{self._get_line_number()} G43 H{self.tool_number}")  # 刀具长度补偿
        return header
    
    def generate_footer(self):
        """生成Haas程序尾"""
        footer = []
        footer.append(f"N{self._get_line_number()} G00 Z{self.format_coordinate(self.safety_height)}")
        footer.append(f"N{self._get_line_number()} G00 X0. Y0.")
        footer.append(f"N{self._get_line_number()} M05")  # 主轴停止
        footer.append(f"N{self._get_line_number()} M30")  # 程序结束
        footer.append("%")
        return footer
    
    def generate_linear_move(self, x, y, z, feed=None):
        """生成Haas直线移动指令(G01)"""
        if feed is None:
            feed = self.feed_rate
            
        cmd = f"N{self._get_line_number()} G01"
        
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}."
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}."
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}."
            self.current_position["z"] = z
            
        cmd += f" F{feed}."
        
        return cmd
    
    def generate_rapid_move(self, x=None, y=None, z=None):
        """生成Haas快速移动指令(G00)"""
        cmd = f"N{self._get_line_number()} G00"
        
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}."
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}."
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}."
            self.current_position["z"] = z
            
        return cmd
    
    def set_working_plane(self, plane="xy"):
        """设置Haas工作平面"""
        if plane == "xy":
            return f"N{self._get_line_number()} G17"
        elif plane == "xz":
            return f"N{self._get_line_number()} G18"
        elif plane == "yz":
            return f"N{self._get_line_number()} G19"
        else:
            raise ValueError(f"不支持的平面: {plane}")
    
    def set_units(self, units="mm"):
        """设置Haas单位"""
        if units == "mm":
            return f"N{self._get_line_number()} G21"
        elif units == "inch":
            return f"N{self._get_line_number()} G20"
        else:
            raise ValueError(f"不支持的单位: {units}")
    
    def set_coordinate_system(self, system=1):
        """设置Haas坐标系"""
        if 1 <= system <= 6:
            g_code = 53 + system  # G54-G59
            return f"N{self._get_line_number()} G{g_code}"
        else:
            raise ValueError(f"坐标系编号必须在1-6范围内，当前值: {system}")
    
    def tool_radius_comp_on(self, direction="left"):
        """刀具半径补偿开启"""
        if direction == "left":
            return f"N{self._get_line_number()} G41 D{self.tool_number}"
        elif direction == "right":
            return f"N{self._get_line_number()} G42 D{self.tool_number}"
        else:
            raise ValueError(f"不支持的补偿方向: {direction}")
    
    def tool_radius_comp_off(self):
        """刀具半径补偿关闭"""
        return f"N{self._get_line_number()} G40"
    
    def coolant_on(self, type="flood"):
        """冷却液开启"""
        if type == "flood":
            return f"N{self._get_line_number()} M08"
        elif type == "mist":
            return f"N{self._get_line_number()} M07"
        else:
            raise ValueError(f"不支持的冷却类型: {type}")
    
    def coolant_off(self):
        """冷却液关闭"""
        return f"N{self._get_line_number()} M09"
        
    def circular_move(self, x, y, z=None, i=None, j=None, k=None, direction="cw", feed=None):
        """
        生成圆弧移动指令
        
        参数:
        x, y, z: 终点坐标
        i, j, k: 相对于起点的圆心偏移量
        direction: 方向，"cw"为顺时针，"ccw"为逆时针
        feed: 进给速率
        """
        if feed is None:
            feed = self.feed_rate
            
        if direction == "cw":
            cmd = f"N{self._get_line_number()} G02"
        else:
            cmd = f"N{self._get_line_number()} G03"
            
        if x is not None:
            cmd += f" X{self.format_coordinate(x)}."
            self.current_position["x"] = x
            
        if y is not None:
            cmd += f" Y{self.format_coordinate(y)}."
            self.current_position["y"] = y
            
        if z is not None:
            cmd += f" Z{self.format_coordinate(z)}."
            self.current_position["z"] = z
            
        if i is not None:
            cmd += f" I{self.format_coordinate(i)}."
            
        if j is not None:
            cmd += f" J{self.format_coordinate(j)}."
            
        if k is not None:
            cmd += f" K{self.format_coordinate(k)}."
            
        cmd += f" F{feed}."
        
        return cmd 